included:
  – ../ButtonKit
  – ../ButtonGallery

disabled_rules:
  – compiler_protocol_init
  – cyclomatic_complexity
  – file_length
  – force_cast
  – function_body_length
  – function_parameter_count
  – identifier_name
  – multiple_closures_with_trailing_closure
  – notification_center_detachment
  – line_length
  – trailing_whitespace
  – type_body_length
  – type_name
  – todo

opt_in_rules:
  – anyobject_protocol
  – array_init
  – closure_end_indentation
  – closure_spacing
  – collection_alignment
  – contains_over_filter_count
  – contains_over_filter_is_empty
  – contains_over_first_not_nil
  – contains_over_range_nil_comparison
  – convenience_type
  – discouraged_object_literal
  – discouraged_optional_boolean
  – empty_collection_literal
  – empty_count
  – empty_string
  – empty_xctest_method
  – enum_case_associated_values_count
  – expiring_todo
  – explicit_init
  – fallthrough
  – fatal_error_message
  – file_name_no_space
  – first_where
  – flatmap_over_map_reduce
  – identical_operands
  – joined_default_parameter
  – last_where
  – legacy_multiple
  – legacy_random
  – literal_expression_end_indentation
  – lower_acl_than_parent
# useful for frameworks with public interface  – missing_docs
  – multiline_function_chains
  – multiline_parameters
  – multiline_parameters_brackets
  – nslocalizedstring_key
  – operator_usage_whitespace
  – optional_enum_case_matching
  – overridden_super_call
  – override_in_extension
  – pattern_matching_keywords
  – prefer_self_type_over_type_of_self
  – prefer_zero_over_explicit_init
  – private_outlet
  – prohibited_super_call
  – reduce_into
  – redundant_nil_coalescing
  – redundant_type_annotation
  – single_test_class
  – sorted_first_last
  – sorted_imports
  – static_operator
  – toggle_bool
  – unneeded_parentheses_in_closure_argument
  – unused_declaration
  – unused_import
  – vertical_parameter_alignment_on_call
  – vertical_whitespace_closing_braces
  
# if {
# }
# else {
# }
statement_position:
  statement_mode: uncuddled_else
