# This workflow will build a Swift iOS App
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild -scheme AveBingo \
           -project AveBingo.xcodeproj \
           -destination 'platform=iOS Simulator,name=iPhone 15'
